import Box from "./Box";
import "./HowToAiverse.css";
import Tech from "../../assets/images/logo4.png";
import Photo from "../../assets/images/robot3.png";

function HowAiverse() {
  return (
    <div className="aiversebg" id="about" style={{ position: "relative" }}>
      <div className="howToFilter"></div>
      <div className="top-header">
        <h1 className="header-aiverse">How do Aiverse NFTs work?</h1>
        <p className="p1">
          Aiverse nft are minted from images generated by two ai models working
          in sync. They are based on one of the biggest models ever trained in
          Russia.
          {/* <br /> */}
          These nfts signify ownership and access to a no. of features coming in
          future
        </p>
      </div>
      <img src={Tech} className="techImg" />
      <div style={{ position: "absolute", bottom: "0", marginLeft: "12%" }}>
        <img src={Photo} className="robot" />
        <Box />
      </div>
    </div>
  );
}

export default HowAiverse;
